version: '3.8'

services:
  web:
    build: .
    restart: always
    environment:
      - NODE_ENV=production
      # Add your specific app ENVs here if needed
    ports:
      - "4321:4321"

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
